### PR TITLE
Setup dignified.js

### PR DESCRIPTION
**Pull request by dignifiedquire**
At the moment tests are failing in phantomjs, no idea why. cc @nginnever @diasdavid 

Ref https://github.com/dignifiedquire/dignified.js/issues/1

### CODE REVIEW

**Comment by diasdavid** [comment]
@dignifiedquire  could you rebase master onto your PR? We've now 100% green on master, thanks to @noffle's finding

**Comment by dignifiedquire** [comment]
@diasdavid done

**Comment by diasdavid** [comment]
@dignifiedquire I was rebasing master onto this branch and found that tests error on PhantomJS run:

```
  1) IPFS data importing tests on the Browser layout: importer import a big buffer:
     AssertionError: expected 1311038 to equal 1258318 (/Users/ground-control/code/protocol-labs/_ipfs/js/js-ipfs-data-importing/test/browser.js:45552)
```

Do you also see this in your machine?

//cc @nginnever

**Comment by nginnever** [comment]
I just pulled this PR and wasn't able to repro the PhantomJS error.

**Pull request merged**
